version: '3'

volumes:
  pg_data:
  static:
  media:
  data:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: foodgram_db

  backend:
    image: smirev/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/foodgram/media/
      - data:/app/data/
    environment:
      - SENTRY_DSN=https://1639218d8c281fb6c487b5043ff509d3@o4505855077842944.ingest.sentry.io/4505855079612416
    container_name: foodgram_backend

  frontend:
    image: smirev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - db
      - backend
    volumes:
      - static:/frontend_static
    container_name: foodgram_frontend

  nginx:
    image: smirev/foodgram_nginx
    env_file: .env
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 8000:80
    container_name: foodgram_nginx
