# Generated by Django 3.2 on 2023-08-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/no_photo.jpg', upload_to='images/'),
        ),
    ]
